apiVersion: apps/v1
kind: Deployment
metadata:
  name: dish-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dish-service
  template:
    metadata:
      labels:
        app: dish-service
    spec:
      containers:
      - name: dish-service
        image: anjalimishra26/dish_service:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_APP
          value: "app.py"
