apiVersion: v1
kind: Service
metadata:
  name: dish-service
spec:
  selector:
    app: dish-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30001 
  type: NodePort
