apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: scalableservice/order_service:updated
        ports:
        - containerPort: 5002
        env:
        - name: FLASK_APP
          value: "app.py"
